name: HEXO CI

on:
  push:
    branches:
    - master
    
jobs:
  build:
    name: A job to deploy blog.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true # Checkout private submodules(themes or something else).

      # Caching dependencies to speed up workflows. (GitHub will remove any cache entries that have not been accessed in over 7 days.)
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12' #超过12的版本有几个warning，我不想处理
      - name: Configuration environment
        env:
          # 定义了一个变量，对应secrets-actions里面配置的私钥的名字
          HEXO_DEPLOY_KEY_PRI: ${{secrets.HEXO_DEPLOY_KEY_PRI}}
        run: |
          # 创建了一个ssh文件夹
          mkdir -p ~/.ssh/
          # 把key复制进去
          echo "$HEXO_DEPLOY_KEY_PRI" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          # 配置git
          git config --global user.name "hechengdong"
          git config --global user.email "569186076@qq.com"
      - name: Install dependencies
        run: |
          # 安装hexo
          npm i -g hexo-cli
          npm i
      - name: Deploy
        run: |
          hexo clean && hexo generate && hexo deploy